import type { Treatment } from "@/types";

export const treatments: Treatment[] = [
  {
    id: "tx-1",
    name: "Botox",
    category: "Injectables",
    avgPrice: 425,
    optimalInterval: "12-16 weeks",
    optimalDays: 98,
    activeClients: 187,
    rebookingRate: 0.68,
    revenueImpact: 79475,
  },
  {
    id: "tx-2",
    name: "Dermal Fillers",
    category: "Injectables",
    avgPrice: 750,
    optimalInterval: "6-12 months",
    optimalDays: 270,
    activeClients: 94,
    rebookingRate: 0.52,
    revenueImpact: 70500,
  },
  {
    id: "tx-3",
    name: "Laser Hair Removal",
    category: "Body",
    avgPrice: 295,
    optimalInterval: "4-6 weeks",
    optimalDays: 35,
    activeClients: 156,
    rebookingRate: 0.71,
    revenueImpact: 46020,
  },
  {
    id: "tx-4",
    name: "Chemical Peels",
    category: "Skin",
    avgPrice: 185,
    optimalInterval: "4-6 weeks",
    optimalDays: 35,
    activeClients: 63,
    rebookingRate: 0.45,
    revenueImpact: 11655,
  },
  {
    id: "tx-5",
    name: "Microneedling",
    category: "Skin",
    avgPrice: 350,
    optimalInterval: "4-6 weeks",
    optimalDays: 35,
    activeClients: 41,
    rebookingRate: 0.58,
    revenueImpact: 14350,
  },
  {
    id: "tx-6",
    name: "HydraFacial",
    category: "Skin",
    avgPrice: 199,
    optimalInterval: "Monthly",
    optimalDays: 30,
    activeClients: 112,
    rebookingRate: 0.74,
    revenueImpact: 22288,
  },
];
